apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: redis 
  # namespace: example-voting-app 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels:
        app: redis 
    spec:
      containers:
      - name: redis 
        image: redis:alpine 
        volumeMounts:
        - name: healthchecks 
          mountPath: /healthchecks 
        readinessProbe:
          exec:
            command:
            - sh 
            - /healthchecks/redis.sh  
          initialDelaySeconds : 5  
          periodSeconds : 10  
      volumes :
      - name : healthchecks  
        configMap :
          name : healthchecks-config  
      restartPolicy : Always  

---
apiVersion : v1  
kind : Service  
metadata :
  name : redis  
  # namespace : example-voting-app  
spec :
  ports :
    - port : 6379  
      targetPort : 6379  
  selector :
    app : redis  
